Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -94,11 +94,23 @@ stages:
         PipelineId: '$(AMLPIPELINE_ID)'
         ExperimentName: '$(EXPERIMENT_NAME)'
         PipelineParameters: '"ParameterAssignments": {"model_name": "$(MODEL_NAME)"}, "tags": {"BuildId": "$(Build.BuildId)", "BuildUri": "$(BUILD_URI)"}, "StepTags": {"BuildId": "$(Build.BuildId)", "BuildUri": "$(BUILD_URI)"}'
-#  - job: "Training_Run_Report"
-#    dependsOn: "Run_ML_Pipeline"
-#    condition: always()
-#    displayName: "Determine if evaluation succeeded and new model is registered"
-#    container: mlops
-#    timeoutInMinutes: 0
-#    steps:
-#    - template: get-model-version-template.yml
+  - job: "Training_Pipeline"
+    dependsOn: "Run_ML_Pipeline"
+    condition: always()
+    displayName: "Determine if evaluation succeeded and new model is registered"
+    container: mlops
+    timeoutInMinutes: 0
+    steps:
+    - task: AzureCLI@1
+      inputs:
+        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+        scriptLocation: inlineScript
+        inlineScript: |
+          set -e # fail on error
+          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+          python -m ml_service.pipelines.verify_train_pipeline --build_id $(modelbuildid) --output_model_version_file "model_version.txt"
+          # Output model version to Azure DevOps job
+          MODEL_VERSION="$(cat model_version.txt)"
+          echo "##vso[task.setvariable variable=MODEL_VERSION]$MODEL_VERSION"
+      name: 'getversion'
+      displayName: "Determine if evaluation succeeded and new model is registered"
